# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bf79a6b075ba9e41a994c7df7a0add9be767b4d71f4ae7c6318131311a820e4fb6884128eddbcd386791116d8410496469d33fd747960662d08fa0a7ee71c7b

test:
  secret_key_base: 0133b72a3c6863058e4d9f909415463b5f1b163bd26f822c9b8e8fd6ed55411181e25f3620d41e3f2c3a6849491f1ea750962ac1677d5328f7776d94c823ff53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
